apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: guestbook-ui
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - http:
      paths:
      - path: /guestbook
        backend:
          service:
            name: guestbook-ui
            port:
              number: 80
        pathType: Exact