apiVersion: v1
kind: Pod
metadata:
  name: hello-world-message
  labels:
    app: hello-world-message
spec:
  containers:
  - image: "docker.io/steadweb/nodejs-env:latest"
    name: hello-world-message
    env:
      - name: MESSAGE
        valueFrom:
          configMapKeyRef:
            name: hello-world-message
            key: MESSAGE
    ports:
    - containerPort: 8000
      protocol: TCP